# Generated by Django 3.2.9 on 2022-03-31 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220331_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 17, 40, 29, 740092)),
        ),
    ]
